import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.95
decorations = "Full"

[window.padding]
x = 0
y = 0

[font]
size = 14

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001b[27;5;9~"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u001b[27;5;9~"
